# Configuration file
general_settings:
    # Worlds that Chance cubes should not generate in [default: ]
    BlockedWorlds: []

    # true if Chance Cubes should generate as chest loot in the world. false if they should not [default: true]
    ChestLoot: true

    # true if Chance Cubes should have a crafting recipe. false if they should not [default: true]
    CraftingRecipe: true

    # Set to true if the D20's should have any chance value from -100 to 100. Set to false to have the D20's only have a chance value of either -100 or 100 [default: false]
    D20UseNormalChanceValues: false

    # Set to true if the default rewards should be loaded, false if they shouldn't [default: true]
    EnableDefaultRewards: true

    # How many blocks above the Chance Cube that a block that will fall should be droped from [range: 0 ~ 256, default: 20]
    FallingBlockDropHeight: 20

    # true if Chance Cubes should generate like ores with in the world. false if they should not [default: true]
    GenerateAsOre: true

    # true if Chance Cubes should generate on the surface of the world. false if they should not [default: true]
    GenerateOnSurface: true

    # Don't touch! Well I mean you can touch it, if you want. I can't stop you. I'm only text.
    HolidayRewardTriggered: false

    # Set to false if you wish to disable the super special holiday rewards. Why would you want to do that? [default: true]
    HolidayRewards: true

    # true if Chance Cubes should load in user specific rewards (for a select few only) [default: true]
    UserSpecificRewards: true

    # The maximum chance range value. Changes the range of chance that the chance block can pick from. i.e. If you have your range set to default 20. A chance cube with a chance value of 0 can get rewards of -20 to 20 in chance value. [range: 0 ~ 100, default: 20]
    chanceRangeMax: 20

    # The minimum chance range value. Changes the range of chance that the chance block can pick from. i.e. If you have your range set to default 20. A chance cube with a chance value of 0 can get rewards of -20 to 20 in chance value. [range: 0 ~ 100, default: 20]
    chanceRangeMin: 20

    # Amount of chance cubes to try and spawn, per chunk, as an ore [range: 1 ~ 100, default: 4]
    oreGenAmount: 4

    # Number of uses for a pendant [range: 0 ~ 1000, default: 32]
    pendantUses: 32

    # Percentage chance of a chunk to have a chance cube spawned on the surface. [range: 0 ~ 100, default: 1]
    surfaceGenAmount: 1

giant_chance_cube_rewards:
    #  [default: true]
    "chancecubes:BioDome": true

    #  [default: true]
    "chancecubes:Chuck_Reverse": true

    #  [default: true]
    "chancecubes:Chunk_Flip": true

    #  [default: true]
    "chancecubes:Floor_Is_Lava": true

    #  [default: true]
    "chancecubes:Fluid_Tower": true

    #  [default: true]
    "chancecubes:Ore_Pillars": true

    #  [default: true]
    "chancecubes:Ore_Sphere": true

    #  [default: true]
    "chancecubes:Raining_Potions": true

    #  [default: true]
    "chancecubes:TNT_Throw": true

    #  [default: true]
    "chancecubes:Trowables": true

    #  [default: true]
    "chancecubes:Village": true

##########################################################################################################
# rewards
#--------------------------------------------------------------------------------------------------------#
# Set to false to disable a specific reward
##########################################################################################################

rewards:
    #  [default: true]
    "chancecubes:5_Prongs": true

    #  [default: true]
    "chancecubes:Actual_Invisible_Ghast": true

    #  [default: true]
    "chancecubes:Anti_Slab": true

    #  [default: true]
    "chancecubes:AnvilRain": true

    #  [default: true]
    "chancecubes:Armor_Stand_Armor": true

    #  [default: true]
    "chancecubes:Beacon_Build": true

    #  [default: true]
    "chancecubes:BedRock": true

    #  [default: true]
    "chancecubes:Bone_Cat": true

    #  [default: true]
    "chancecubes:Book_Of_Memes": true

    #  [default: true]
    "chancecubes:Bookshelves": true

    #  [default: true]
    "chancecubes:Cake": true

    #  [default: true]
    "chancecubes:Chance_Cube_Cube": true

    #  [default: true]
    "chancecubes:Charged_Creeper": true

    #  [default: true]
    "chancecubes:ChatMessage": true

    #  [default: false]
    "chancecubes:Clear_Inventory": false

    #  [default: true]
    "chancecubes:Coal_To_Diamonds": true

    #  [default: true]
    "chancecubes:Cookie_Monster": true

    #  [default: true]
    "chancecubes:D-rude_SandStorm": true

    #  [default: true]
    "chancecubes:DIY_Pie": true

    #  [default: true]
    "chancecubes:Diamond_Block": true

    #  [default: true]
    "chancecubes:Did_You_Know": true

    #  [default: true]
    "chancecubes:Disco": true

    #  [default: true]
    "chancecubes:Divine": true

    #  [default: true]
    "chancecubes:Double_Rainbow": true

    #  [default: true]
    "chancecubes:EXP": true

    #  [default: true]
    "chancecubes:EXP_Shower": true

    #  [default: true]
    "chancecubes:Enchanting": true

    #  [default: true]
    "chancecubes:Ender_Crystal_Timer": true

    #  [default: true]
    "chancecubes:Explorer": true

    #  [default: true]
    "chancecubes:Explosion": true

    #  [default: true]
    "chancecubes:Fake_TNT": true

    #  [default: true]
    "chancecubes:Farmer": true

    #  [default: true]
    "chancecubes:Fighter": true

    #  [default: true]
    "chancecubes:Finding_Marlin": true

    #  [default: true]
    "chancecubes:Finding_Nemo": true

    #  [default: true]
    "chancecubes:Fire_Aspect_Fire": true

    #  [default: true]
    "chancecubes:Fireworks": true

    #  [default: true]
    "chancecubes:Fish_Dog": true

    #  [default: false]
    "chancecubes:Giant_Chance_Cube": false

    #  [default: true]
    "chancecubes:Giga_Breaker": true

    #  [default: true]
    "chancecubes:Half_Fishingrod": true

    #  [default: true]
    "chancecubes:Half_Heart": true

    #  [default: true]
    "chancecubes:Have_Another": true

    #  [default: true]
    "chancecubes:Hearts": true

    #  [default: true]
    "chancecubes:Help_Me": true

    #  [default: true]
    "chancecubes:Herobrine": true

    #  [default: true]
    "chancecubes:Horde": true

    #  [default: true]
    "chancecubes:Hot_Tub": true

    #  [default: true]
    "chancecubes:Icsahedron": true

    #  [default: true]
    "chancecubes:Inventory_Bomb": true

    #  [default: true]
    "chancecubes:Invisible_Creeper": true

    #  [default: true]
    "chancecubes:Invisible_Ghasts": true

    #  [default: true]
    "chancecubes:Item_Of_Destiny": true

    #  [default: true]
    "chancecubes:Item_Rename": true

    #  [default: true]
    "chancecubes:Juke_Box": true

    #  [default: true]
    "chancecubes:Knockback_Zombie": true

    #  [default: true]
    "chancecubes:Lava_Ring": true

    #  [default: true]
    "chancecubes:Math": true

    #  [default: true]
    "chancecubes:Maze": true

    #  [default: true]
    "chancecubes:Mitas": true

    #  [default: true]
    "chancecubes:Nether_Jelly_Fish": true

    #  [default: true]
    "chancecubes:Nether_Star": true

    #  [default: true]
    "chancecubes:No": true

    #  [default: true]
    "chancecubes:No_Exp": true

    #  [default: true]
    "chancecubes:Notch": true

    #  [default: true]
    "chancecubes:Nuke": true

    #  [default: true]
    "chancecubes:One_Is_Lucky": true

    #  [default: true]
    "chancecubes:One_Man_Army": true

    #  [default: true]
    "chancecubes:One_Shot": true

    #  [default: true]
    "chancecubes:Ores_Galore": true

    #  [default: true]
    "chancecubes:Path_To_Succeed": true

    #  [default: true]
    "chancecubes:Pig_Of_Destiny": true

    #  [default: true]
    "chancecubes:Poison": true

    #  [default: true]
    "chancecubes:Question": true

    #  [default: true]
    "chancecubes:Quidditch": true

    #  [default: true]
    "chancecubes:Rain": true

    #  [default: true]
    "chancecubes:Rancher": true

    #  [default: true]
    "chancecubes:Random_Teleport": true

    #  [default: true]
    "chancecubes:Redstone_Diamond": true

    #  [default: true]
    "chancecubes:Remove_Useful_Stuff": true

    #  [default: true]
    "chancecubes:Roosevelt's_Stick": true

    #  [default: true]
    "chancecubes:Rotten_Food": true

    #  [default: true]
    "chancecubes:STRING!": true

    #  [default: true]
    "chancecubes:Sail_Away": true

    #  [default: true]
    "chancecubes:Saplings": true

    #  [default: true]
    "chancecubes:Sethbling_Reward": true

    #  [default: true]
    "chancecubes:Silverfish_Surround": true

    #  [default: true]
    "chancecubes:Silvermite_Stacks": true

    #  [default: true]
    "chancecubes:SkyBlock": true

    #  [default: true]
    "chancecubes:SlimeMan": true

    #  [default: true]
    "chancecubes:Smite": true

    #  [default: true]
    "chancecubes:Spawn_Cluckington": true

    #  [default: true]
    "chancecubes:Spawn_Dr_Trayaurus": true

    #  [default: true]
    "chancecubes:Spawn_Glenn": true

    #  [default: true]
    "chancecubes:Spawn_Jerry": true

    #  [default: true]
    "chancecubes:Spawn_Pickles": true

    #  [default: true]
    "chancecubes:SpongeBob_SquarePants": true

    #  [default: true]
    "chancecubes:Squid_Horde": true

    #  [default: true]
    "chancecubes:Surrounded": true

    #  [default: true]
    "chancecubes:Surrounded_Creeper": true

    #  [default: true]
    "chancecubes:TNT_Bats": true

    #  [default: true]
    "chancecubes:TNT_Cat": true

    #  [default: true]
    "chancecubes:TNT_Diamond": true

    #  [default: true]
    "chancecubes:Table_Flip": true

    #  [default: true]
    "chancecubes:Take_This": true

    #  [default: true]
    "chancecubes:Thrown_In_Air": true

    #  [default: true]
    "chancecubes:Tnt_Structure": true

    #  [default: true]
    "chancecubes:Torches_To_Creepers": true

    #  [default: true]
    "chancecubes:TrollHole": true

    #  [default: true]
    "chancecubes:TrollTNT": true

    #  [default: true]
    "chancecubes:Wait_For_It": true

    #  [default: true]
    "chancecubes:Want_To_Build_A_Snowman": true

    #  [default: true]
    "chancecubes:Watch_World_Burn": true

    #  [default: true]
    "chancecubes:Witch": true

    #  [default: true]
    "chancecubes:Wither": true

    #  [default: true]
    "chancecubes:Wolves_To_Creepers": true

    #  [default: true]
    "chancecubes:Wool": true

    #  [default: true]
    "chancecubes:XP_Crystal": true

    #  [default: true]
    "chancecubes:pssst": true
